### your site title here

title: Joko Saptono
description: Someone who Ingin Menjadi Programmer Handal Namun Enggan Ngoding

baseurl: "/web-portfolio-v1"
url: "https://josapton.github.io"
email: "josapton@gmail.com"

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "jokosaptono"
# stackoverflow: "#"
github: "josapton"
# researchgate: "#"
# orcid: "#"
# quora: "#"
instagram: "josapton"
facebook: "josapton"
# bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - redirect.md
      - my-gh-pages.md
      - revou-coding-camp-mini-project.md
      - capstone-data-analysis.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
